export enum AccessLogAction {
  // ===========================
  // ACESSOS
  // ===========================
  LISTA_UTILIZADORES = 'LISTA_UTILIZADORES',
  CRIAR_UTILIZADOR = 'CRIAR_UTILIZADOR',
  ACESSO_FUNCIONALIDADE_GRUPO = 'ACESSO_FUNCIONALIDADE_GRUPO',
  ACESSO_TODOS = 'ACESSO_TODOS',
  CARGOS_REITORIA = 'CARGOS_REITORIA',
  LOGS_ACESSO = 'LOGS_ACESSO',
  UTILIZADORES_LOGADOS = 'UTILIZADORES_LOGADOS',
  GRUPOS = 'GRUPOS',

  // ===========================
  // EXAME DE ACESSO
  // ===========================
  ADMITIR_CANDIDATO = 'ADMITIR_CANDIDATO',
  ALTERAR_SENHA_CANDIDATO = 'ALTERAR_SENHA_CANDIDATO',
  ATRIBUIR_PROVA = 'ATRIBUIR_PROVA',
  CONSULTAR_PROVA = 'CONSULTAR_PROVA',
  ESTATISTICAS_EXAME = 'ESTATISTICAS_EXAME',
  ESTATISTICAS_DIARIA = 'ESTATISTICAS_DIARIA',
  INSCRICAO_EPOCA_ESPECIAL = 'INSCRICAO_EPOCA_ESPECIAL',
  LANCAR_NOTA_ARQUITECTURA = 'LANCAR_NOTA_ARQUITECTURA',
  LANCAR_NOTA_MANUAL = 'LANCAR_NOTA_MANUAL',
  LISTA_CANDIDATOS = 'LISTA_CANDIDATOS',
  CANDIDATOS_ADMITIDOS = 'CANDIDATOS_ADMITIDOS',
  PROVAS_POR_CANDIDATO = 'PROVAS_POR_CANDIDATO',
  RESULTADOS_FINAIS = 'RESULTADOS_FINAIS',
  HORARIOS_CURSO = 'HORARIOS_CURSO',
  PAUTA_GERAL_EXAME = 'PAUTA_GERAL_EXAME',
  RESETAR_PROVA = 'RESETAR_PROVA',
  LISTA_PRESENCA_EXAME = 'LISTA_PRESENCA_EXAME',
  CANDIDATOS_COM_SEM_PROVA = 'CANDIDATOS_COM_SEM_PROVA',
  TOPICOS_PROVA = 'TOPICOS_PROVA',
  PERGUNTAS_PROVA = 'PERGUNTAS_PROVA',
  PROVAS = 'PROVAS',
  CONFIGURAR_VAGAS = 'CONFIGURAR_VAGAS',

  // ===========================
  // INSCRIÇÕES
  // ===========================
  ESTATISTICAS_INSCRICOES = 'ESTATISTICAS_INSCRICOES',
  MATRICULADOS = 'MATRICULADOS',
  SEM_INSCRICAO_UC = 'SEM_INSCRICAO_UC',
  SEM_INSCRICAO_CURSO = 'SEM_INSCRICAO_CURSO',
  ESTADO_HORARIO = 'ESTADO_HORARIO',
  INSCRITOS_UC = 'INSCRITOS_UC',
  LISTAGEM_GERAL_ESTUDANTES = 'LISTAGEM_GERAL_ESTUDANTES',
  ESTADO_MATRICULA = 'ESTADO_MATRICULA',
  ISENTAR_COLISAO = 'ISENTAR_COLISAO',
  ESTUDANTES_DIPLOMADOS = 'ESTUDANTES_DIPLOMADOS',

  // ===========================
  // CALENDÁRIO
  // ===========================
  ACTIVIDADES_LECTIVAS = 'ACTIVIDADES_LECTIVAS',
  PRAZOS_ACADEMICOS = 'PRAZOS_ACADEMICOS',
  DIAS_ISENTOS = 'DIAS_ISENTOS',
  PARAMETROS_CALENDARIO = 'PARAMETROS_CALENDARIO',
  CONFIGURACAO_ANO_LECTIVO = 'CONFIGURACAO_ANO_LECTIVO',

  // ===========================
  // HORÁRIOS
  // ===========================
  CRIAR_HORARIO = 'CRIAR_HORARIO',
  HORARIOS_SEMANAIS = 'HORARIOS_SEMANAIS',
  DOCENTES_SUBSTITUTOS = 'DOCENTES_SUBSTITUTOS',
  MOVIMENTAR_ESTUDANTES = 'MOVIMENTAR_ESTUDANTES',
  PERMISSAO_EDITAR_HORARIO = 'PERMISSAO_EDITAR_HORARIO',
  HORARIOS_DOCENTE = 'HORARIOS_DOCENTE',
  INSCRICOES_HORARIO = 'INSCRICOES_HORARIO',
  LISTAR_HORARIOS = 'LISTAR_HORARIOS',
  HORARIOS_ELIMINADOS = 'HORARIOS_ELIMINADOS',
  HORARIOS_SALA = 'HORARIOS_SALA',
  HORARIOS_UC = 'HORARIOS_UC',
  PARAMETROS_HORARIOS = 'PARAMETROS_HORARIOS',

  // ===========================
  // AVALIAÇÕES
  // ===========================
  CONTROLE_LANCAMENTO = 'CONTROLE_LANCAMENTO',
  FORMULA_UC = 'FORMULA_UC',
  FORMULA_ORAL = 'FORMULA_ORAL',
  ESTATISTICAS_NOTAS = 'ESTATISTICAS_NOTAS',
  ESTUDANTES_AVALIACAO = 'ESTUDANTES_AVALIACAO',
  HISTORICO_LANCAMENTO = 'HISTORICO_LANCAMENTO',
  LANCAMENTO_PAUTA = 'LANCAMENTO_PAUTA',
  LANCAMENTO_NOTAS = 'LANCAMENTO_NOTAS',
  LISTA_PRESENCA = 'LISTA_PRESENCA',
  PAUTA_GERAL = 'PAUTA_GERAL',
  PAUTA_UC = 'PAUTA_UC',
  PERMISSAO_FORA_PRAZO = 'PERMISSAO_FORA_PRAZO',
  VALIDACAO_PAUTA = 'VALIDACAO_PAUTA',
  VISUALIZAR_NOTAS = 'VISUALIZAR_NOTAS',
  PARAMETROS_AVALIACAO = 'PARAMETROS_AVALIACAO',

  // ===========================
  // FINANÇAS
  // ===========================
  MENSALIDADES_PAGAS = 'MENSALIDADES_PAGAS',
  NOTAS_PAGAMENTO = 'NOTAS_PAGAMENTO',
  SERVICOS_EMOLUMENTOS = 'SERVICOS_EMOLUMENTOS',
  NEGOCIACAO_DIVIDA = 'NEGOCIACAO_DIVIDA',
  TIPOS_CREDITO = 'TIPOS_CREDITO',
  INSTITUICOES = 'INSTITUICOES',
  CREDITO_EDUCACIONAL = 'CREDITO_EDUCACIONAL',
  BOLSEIROS = 'BOLSEIROS',
  ATRIBUIR_CREDITO = 'ATRIBUIR_CREDITO',
  CONTRATOS_INSTITUICAO = 'CONTRATOS_INSTITUICAO',
  DESCONTOS = 'DESCONTOS',
  ATRIBUIR_DESCONTO = 'ATRIBUIR_DESCONTO',
  PAGAMENTOS = 'PAGAMENTOS',
  PAGAMENTO_TFC = 'PAGAMENTO_TFC',
  ISENCAO_SERVICO = 'ISENCAO_SERVICO',
  FORMA_PAGAMENTO = 'FORMA_PAGAMENTO',
  CAIXAS = 'CAIXAS',
  MEU_CAIXA = 'MEU_CAIXA',

  // ===========================
  // COMUNICAÇÃO
  // ===========================
  AVISOS = 'AVISOS',
  SOLICITACOES_ENCAMINHADAS = 'SOLICITACOES_ENCAMINHADAS',
  SOLICITACOES = 'SOLICITACOES',
  IMAGEM_ABERTURA = 'IMAGEM_ABERTURA',

  // ===========================
  // SUPORTE
  // ===========================
  SOLICITACOES_SUPORTE = 'SOLICITACOES_SUPORTE',
  TIPOS_SUPORTE = 'TIPOS_SUPORTE',

  // ===========================
  // DOCUMENTOS
  // ===========================
  VALIDAR_DOCUMENTOS = 'VALIDAR_DOCUMENTOS',
}
