-- =====================================================================
-- Migration: Identity & Platform Access
-- Base de dados: Oracle
--
-- NÃO altera, nem referencia por FK, nenhuma tabela existente do Auth
-- (FK2_*, GP_*, UMA_TB_ANO_LECTIVO, etc.). Cria apenas tabelas novas
-- para a nova camada Identity -> Platform Access.
--
-- Este projeto não tem uma ferramenta de migrations configurada
-- (TypeORM está com synchronize:false e sem CLI de migrations), por
-- isso este script deve ser aplicado manualmente contra a base de
-- dados, seguindo o mesmo padrão de SQL puro já usado no projeto.
-- =====================================================================

-- ---------------------------------------------------------------------
-- UMA_TB_IDENTITY
-- ---------------------------------------------------------------------
CREATE TABLE GLOBAL_TB_IDENTITY (
  ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  USERNAME    VARCHAR2(100) NOT NULL,
  EMAIL       VARCHAR2(150) NOT NULL,
  NAME        VARCHAR2(200) NOT NULL,
  BI          VARCHAR2(150) NOT NULL,
  AVATAR      VARCHAR2(150) NOT NULL,
  PASSWORD    VARCHAR2(255) NOT NULL,
  STATUS      NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_IDENTITY_USERNAME UNIQUE (USERNAME),
  CONSTRAINT UQ_IDENTITY_EMAIL UNIQUE (EMAIL)
  CONSTRAINT UQ_IDENTITY_BI UNIQUE (BI)
);

-- ---------------------------------------------------------------------
-- UMA_TB_PLATFORM
-- ---------------------------------------------------------------------
CREATE TABLE UMA_TB_PLATFORM (
  ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  CODE        VARCHAR2(50) NOT NULL,
  NAME        VARCHAR2(150) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  STATUS      NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_PLATFORM_CODE UNIQUE (CODE)
);

-- ---------------------------------------------------------------------
-- UMA_TB_USER_PLATFORM
-- Relação Identity <-> Platform. A constraint UQ_USER_PLATFORM impede
-- que o mesmo utilizador seja associado duas vezes à mesma plataforma.
-- ---------------------------------------------------------------------
CREATE TABLE UMA_TB_USER_PLATFORM (
  ID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  USER_ID      NUMBER NOT NULL,
  PLATFORM_ID  NUMBER NOT NULL,
  STATUS       NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_USER_PLATFORM_IDENTITY FOREIGN KEY (USER_ID)
    REFERENCES UMA_TB_IDENTITY (ID),
  CONSTRAINT FK_USER_PLATFORM_PLATFORM FOREIGN KEY (PLATFORM_ID)
    REFERENCES UMA_TB_PLATFORM (ID),
  CONSTRAINT UQ_USER_PLATFORM UNIQUE (USER_ID, PLATFORM_ID)
);

CREATE INDEX IDX_USER_PLATFORM_USER ON UMA_TB_USER_PLATFORM (USER_ID);
CREATE INDEX IDX_USER_PLATFORM_PLATFORM ON UMA_TB_USER_PLATFORM (PLATFORM_ID);

-- ---------------------------------------------------------------------
-- Seed opcional das plataformas mencionadas no pedido
-- ---------------------------------------------------------------------
INSERT INTO UMA_TB_PLATFORM (CODE, NAME, DESCRIPTION) VALUES ('INVOICE', 'Invoice', 'Sistema de facturação');
INSERT INTO UMA_TB_PLATFORM (CODE, NAME, DESCRIPTION) VALUES ('FINANCE', 'Finance', 'Sistema financeiro');
INSERT INTO UMA_TB_PLATFORM (CODE, NAME, DESCRIPTION) VALUES ('ACADEMIC', 'Academic', 'Sistema académico');
INSERT INTO UMA_TB_PLATFORM (CODE, NAME, DESCRIPTION) VALUES ('HR', 'HR', 'Recursos Humanos');
INSERT INTO UMA_TB_PLATFORM (CODE, NAME, DESCRIPTION) VALUES ('CRM', 'CRM', 'Gestão de relacionamento com clientes');

COMMIT;
